Repository FPGA-MAFIA/fpga_mafia, pull requests merged in 2023-06, with the labels that each got.

#292 Enable the UART on the big_core FPGA - WIP with the WB (write birst) …
  FPGA/big_core/de10_lite_big_core.qsf
  FPGA/big_core/de10_lite_big_core_top.sv
  FPGA/uart_io/sv/top.sv
  lotr_orig/pyterminal/src/sequence_abd/load_alive_fpga.txt
  lotr_orig/verif/lotr/tests/AliveTest.c
  lotr_orig/verif/lotr/tests/alive.c
  source/big_core/big_core.sv
  source/big_core/big_core_cr_mem.sv
  source/big_core/big_core_mem_wrap.sv
  source/big_core/big_core_pkg.sv
  source/big_core/big_core_rtl_list.f
  source/big_core/big_core_top.sv
  source/common/common_pkg.sv
  source/common/fifo.sv
  source/fabric/fabric.sv
  source/fabric/fabric_rtl_list.f
  source/fabric/mini_core_tile.sv
  source/mini_core/mini_core_rtl_list.f
  source/mini_core/mini_mem_wrap.sv
  source/mini_core/mini_top.sv
  source/router/fifo_arb.sv
  source/router/next_tile_fifo_arb.sv
  source/router/router.sv
  source/router/router_pkg.sv
  source/router/router_rtl_list.f
  source/uart/gateway/gateway.sv
  source/uart/gateway/transfer_handler_engine/Counter.sv
  source/uart/gateway/transfer_handler_engine/transfer_handler_engine.sv
  source/uart/gateway/transfer_handler_engine/wishbone_transfer_fsm.sv
  source/uart/gateway/uart_config/uart_config.sv
  source/uart/raminfr.v
  source/uart/timescale.v
  source/uart/uart_defines.v
  source/uart/uart_io.sv
  source/uart/uart_io_rtl_list.f
  source/uart/uart_receiver.v
  source/uart/uart_regs.v
  source/uart/uart_rfifo.v
  source/uart/uart_sync_flops.v
  source/uart/uart_tfifo.v
  source/uart/uart_top.v
  source/uart/uart_transmitter.v
  source/uart/uart_wb.v
  source/uart/uart_wrapper.sv
  source/uart/wishbone/wishbone.sv
  source/uart/wishbone/wishbone_mux3to1.sv
  verif/big_core/tb/big_core_tb.sv
  verif/big_core/tests/alive_FPGA.c
  verif/big_core/tests/basic_commands.s
  verif/fabric/tb/fabric_tb.sv
  verif/mini_core/tb/mini_core_tb.sv
  verif/router/tb/router_tb.sv
  verif/sc_core/tests/basic.s
  verif/sc_core/tests/basic_commands.s
Labels: Learning

#293 add back pressure to the fabric request from TB
  FPGA/big_core/de10_lite_big_core.qsf
  source/mini_core/mini_mem_wrap.sv
  source/router/router.sv
  verif/fabric/regress/level0
  verif/fabric/tb/fabric_tb.sv
  verif/fabric/tests/fabric_all_tiles.sv
Labels: verificaiton

#315 Shmuel mafia router
  source/common/fifo.sv
  source/fabric/fabric.sv
  source/mini_core/mini_mem_wrap.sv
  verif/fabric/tb/fabric_tasks.vh
  verif/fabric/tb/fabric_tb.sv
  verif/fabric/tests/fabric_BP_test.sv
  verif/fabric/tests/fabric_alive.sv
  verif/router/tb/router_tb.sv
  verif/router/tests/fifo_arb_Assertion_test.sv
  verif/router/tests/fifo_arb_back_pressure.sv
Labels: bug, verificaiton
