Repository FPGA-MAFIA/fpga_mafia, pull requests merged in 2023-04, with the labels that each got.

#208 Shmuel mafia router
  source/router/router.sv
  source/router/router_pkg.sv
  source/router/router_rtl_list.f
  verif/router/tb/fifo_arb_dut.vh
  verif/router/tb/router_dut.vh
  verif/router/tb/router_tb.sv
  verif/router/tests/alive.sv
  verif/router/tests/alive_router.sv
  verif/router/tests/fifo_arb.sv
  verif/router/tests/fifo_arb_dif_num_active_fifo.sv
  verif/router/tests/simple.sv
  verif/router/tests/single_fifo_full_BW.sv
Labels: build & env

#237 macros - added assertions.
  source/common/macros.sv
  source/router/fifo.sv
  verif/router/tb/router_tb.sv
  verif/router/tests/fifo_arb_Assertion_test.sv
  verif/router/tests/fifo_arb_all_fifo_full_BW.sv
Labels: RTL design

#238 Yeonatan mafia router
  doc/Mesh_Arch/mesh_scratchpad.vsdx
  source/router/next_tile_fifo_arb.sv
  source/router/north_next_tile_fifo_arb.sv
  source/router/router.sv
  source/router/router_pkg.sv
  source/router/router_rtl_list.f
  source/router/south_next_tile_fifo_arb.sv
  verif/router/regress/rerun
  verif/router/tb/fifo_arb_dut.vh
  verif/router/tb/fifo_arb_trk.vh
  verif/router/tb/router_dut.vh
  verif/router/tb/router_tasks.vh
  verif/router/tb/router_tb.sv
  verif/router/tb/router_trk.vh
  verif/router/tests/router_alive.sv
  verif/router/tests/router_send_to_north.sv
  verif/router/tests/router_send_to_south.sv
Labels: RTL design, verificaiton

#243 Shmuel mafia router
  source/router/fifo.sv
  source/router/fifo_arb.sv
  verif/router/regress/level0
  verif/router/regress/level_fail
  verif/router/regress/rerun
  verif/router/tb/fifo_arb_tasks.vh
  verif/router/tb/router_tb.sv
  verif/router/tests/fifo_arb_all_fifo_full_BW.sv
Labels: Learning

#244 FPGA is alive for BIG_CORE
  FPGA/big_core/de10_lite_big_core.qsf
  FPGA/big_core/de10_lite_big_core_top.sv
  FPGA/big_core/mif/d_mem.mif
  FPGA/big_core/mif/i_mem.mif
  FPGA/big_core/sv/i_mem.v
  app/defines/big_core_defines.h
  build.py
  source/big_core/big_core.sv
  source/big_core/big_core_mem_wrap.sv
  source/big_core/big_core_top.sv
  source/big_core/big_core_vga_ctrl.sv
  verif/big_core/tests/alive_FPGA.c
Labels: Learning
